# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opi-lil.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION

# Meta
title: Shallow Learning
tagline: "Cutting edge NLP research" # used by search engines



# Scripts
google_analytics: "UA-61947369-1" # tracking id, e.g. "UA-000000-01"
disqus_shortname:

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_email: "Email"
str_next: "Next"
str_prev: "Prev"
str_continue_reading: "Continue reading"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS

highlighter: rouge
markdown: kramdown
